apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8080
    nodePort: 30010